//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRAZeCards
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOLIDAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOLIDAY()
        {
            this.USER_RESPONSE_INDEX = new HashSet<USER_RESPONSE_INDEX>();
        }
    
        public string Holiday_Id { get; set; }
        public string Holiday_Name { get; set; }
        public string Holiday_Month { get; set; }
        public string Holiday_Date { get; set; }
        public string Holiday_View { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_RESPONSE_INDEX> USER_RESPONSE_INDEX { get; set; }
    }
}
