//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRAZeCards
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_RESPONSE_INDEX
    {
        public int Url_Tracking_Id { get; set; }
        public string Track_Id { get; set; }
    
        public virtual HOLIDAY HOLIDAY { get; set; }
    }
}
